version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: academic-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: academic_db
      POSTGRES_USER: academic
      POSTGRES_PASSWORD: academic123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: academic-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  pgdata:
